data_mesh_gcp:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: analytics # Default dataset
      threads: 4
      timeout_seconds: 300
      location: us-central1
      priority: interactive
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID_PROD') }}"
      dataset: analytics
      threads: 8
      timeout_seconds: 300
      location: us-central1
      priority: batch 