version: 2

sources:
  - name: marketing_raw
    schema: marketing_raw
    tables:
      - name: marketing_events_raw
        description: "Raw marketing events from GCS external table."

models:
  - name: staging_marketing
    description: "Staged marketing events, cleaned and casted."
    columns:
      - name: event_id
        description: "Unique identifier for the event."
        tests:
          - unique
          - not_null
      - name: event_type
        description: "Type of the marketing event (e.g., page_view, form_submit)."
        tests:
          - not_null
      - name: event_timestamp
        description: "Timestamp of when the event occurred."
        tests:
          - not_null
      - name: campaign_id
        description: "Identifier for the marketing campaign."
        tests:
          - not_null
      - name: payload
        description: "JSON payload with event details."
      - name: loaded_at
        description: "Timestamp of when the record was loaded into the raw table."
        tests:
          - not_null 